name: meson_test

on:
  push:
    branches:
      - main
      - v0.2.0
  pull_request:
    branches:
      - main
      - v0.2.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install libwayland-dev

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - run: pip install meson ninja

      - run: meson build
        env:
          CC: clang

      - run: ninja -C build test

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Test_Log
          path: main/build/meson-logs/testlog.txt
